### ISSUE TITLE
Thumbs doesn't have the good rights.

### ISSUE THREAD

**Issue by Misak** [linuxserver/docker-photoshow#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Shouldn't fire the message.

## Current Behavior
Hello, sorry for pulling this up, but I can't get this working. I've used the docker compose from github, changing the directories required and the webpage fails with following message:
`PS_GENERATED dir '/Thumbs/Thumbs/' doesn't exist or doesn't have the good rights.`
I don't see any message in the docker logs, not sure what could cause this.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
`root@infra:/config/gallery# docker --version
Docker version 19.03.13, build 4484c46d9d
root@infra:/config/gallery# uname -a
Linux infra 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/8829330/128597408-cdd98768-6e03-450c-8b03-e97127a03956.png)
Could you please help? Thank you.

**Comment by homerr** [comment]
Who owns the files and directories in `/config` ?

Do an `ls -la /config/gallery` and paste output 

Also would recommend not doing stuff as root user where you can avoid it.

**Comment by Misak** [comment]
This is the owner setups:
![image](https://user-images.githubusercontent.com/8829330/128636638-21261be8-3007-4e28-8ce0-a9d6f95d0856.png)

It is the same every time I run docker-compose for the first time (after removing all directories).

**Comment by Misak** [comment]
I tried to run this gallery on different computer with ubuntu-desktop and it is running without any issues. The privileges on the folders are the same as on the server on which it fails. So not sure where is the difference :/

**Comment by homerr** [comment]
Not sure then, I'd expect the pictures dir being owned by root to cause issues but not the thumbs one. Either way seems like something specific to that server, so we'll close this off and if you do find anything out about the issue hit us up on discord.
